# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_self(object):
    def setupUi(self, self):
        self.setObjectName("self")
        self.resize(1024, 768)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/favicon/favicon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.menuGrande = QtWidgets.QFrame(self.centralwidget)
        self.menuGrande.setGeometry(QtCore.QRect(0, 0, 1021, 108))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuGrande.sizePolicy().hasHeightForWidth())
        self.menuGrande.setSizePolicy(sizePolicy)
        self.menuGrande.setMaximumSize(QtCore.QSize(1021, 16777215))
        self.menuGrande.setObjectName("menuGrande")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menuGrande)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QLabel(self.menuGrande)
        self.logo.setMaximumSize(QtCore.QSize(150, 150))
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.fileLabel = QtWidgets.QVBoxLayout()
        self.fileLabel.setContentsMargins(20, -1, -1, -1)
        self.fileLabel.setObjectName("fileLabel")
        self.fileNameLabel = QtWidgets.QLabel(self.menuGrande)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setBold(True)
        font.setWeight(75)
        self.fileNameLabel.setFont(font)
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.fileLabel.addWidget(self.fileNameLabel)
        self.recordNameLabel = QtWidgets.QLabel(self.menuGrande)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setBold(True)
        font.setWeight(75)
        self.recordNameLabel.setFont(font)
        self.recordNameLabel.setObjectName("recordNameLabel")
        self.fileLabel.addWidget(self.recordNameLabel)
        self.fsLabel = QtWidgets.QLabel(self.menuGrande)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setBold(True)
        font.setWeight(75)
        self.fsLabel.setFont(font)
        self.fsLabel.setObjectName("fsLabel")
        self.fileLabel.addWidget(self.fsLabel)
        self.lenghtSignalLabel = QtWidgets.QLabel(self.menuGrande)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setBold(True)
        font.setWeight(75)
        self.lenghtSignalLabel.setFont(font)
        self.lenghtSignalLabel.setObjectName("lenghtSignalLabel")
        self.fileLabel.addWidget(self.lenghtSignalLabel)
        self.horizontalLayout.addLayout(self.fileLabel)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fileNameText = QtWidgets.QLabel(self.menuGrande)
        self.fileNameText.setObjectName("fileNameText")
        self.verticalLayout_2.addWidget(self.fileNameText)
        self.recordNameText = QtWidgets.QLabel(self.menuGrande)
        self.recordNameText.setObjectName("recordNameText")
        self.verticalLayout_2.addWidget(self.recordNameText)
        self.fsText = QtWidgets.QLabel(self.menuGrande)
        self.fsText.setObjectName("fsText")
        self.verticalLayout_2.addWidget(self.fsText)
        self.lenghtSignalText = QtWidgets.QLabel(self.menuGrande)
        self.lenghtSignalText.setObjectName("lenghtSignalText")
        self.verticalLayout_2.addWidget(self.lenghtSignalText)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(1000000000, 90, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.accionDocumento1 = QtWidgets.QVBoxLayout()
        self.accionDocumento1.setSpacing(0)
        self.accionDocumento1.setObjectName("accionDocumento1")
        self.completeBrief = QtWidgets.QPushButton(self.menuGrande)
        self.completeBrief.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.completeBrief.setObjectName("completeBrief")
        self.accionDocumento1.addWidget(self.completeBrief)
        self.normalGraphic = QtWidgets.QPushButton(self.menuGrande)
        self.normalGraphic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.normalGraphic.setObjectName("normalGraphic")
        self.accionDocumento1.addWidget(self.normalGraphic)
        self.baseLineCorrection = QtWidgets.QPushButton(self.menuGrande)
        self.baseLineCorrection.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.baseLineCorrection.setObjectName("baseLineCorrection")
        self.accionDocumento1.addWidget(self.baseLineCorrection)
        self.horizontalLayout.addLayout(self.accionDocumento1)
        self.accionDocumento2 = QtWidgets.QVBoxLayout()
        self.accionDocumento2.setContentsMargins(-1, -1, 0, -1)
        self.accionDocumento2.setSpacing(0)
        self.accionDocumento2.setObjectName("accionDocumento2")
        self.rDots = QtWidgets.QPushButton(self.menuGrande)
        self.rDots.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rDots.setObjectName("rDots")
        self.accionDocumento2.addWidget(self.rDots)
        self.frequencyMetrics = QtWidgets.QPushButton(self.menuGrande)
        self.frequencyMetrics.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frequencyMetrics.setObjectName("frequencyMetrics")
        self.accionDocumento2.addWidget(self.frequencyMetrics)
        self.pdfExport = QtWidgets.QPushButton(self.menuGrande)
        self.pdfExport.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pdfExport.setObjectName("pdfExport")
        self.accionDocumento2.addWidget(self.pdfExport)
        self.horizontalLayout.addLayout(self.accionDocumento2)
        self.graficaGrande = QtWidgets.QWidget(self.centralwidget)
        self.graficaGrande.setGeometry(QtCore.QRect(0, 100, 1021, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graficaGrande.sizePolicy().hasHeightForWidth())
        self.graficaGrande.setSizePolicy(sizePolicy)
        self.graficaGrande.setMaximumSize(QtCore.QSize(1021, 16777215))
        self.graficaGrande.setObjectName("graficaGrande")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 540, 1021, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(1021, 16777215))
        self.widget.setObjectName("widget")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuAbout_HRV = QtWidgets.QMenu(self.menubar)
        self.menuAbout_HRV.setObjectName("menuAbout_HRV")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(self)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(self)
        self.actionSave.setObjectName("actionSave")
        self.actionDownload = QtWidgets.QAction(self)
        self.actionDownload.setObjectName("actionDownload")
        self.actionExport_PDF = QtWidgets.QAction(self)
        self.actionExport_PDF.setObjectName("actionExport_PDF")
        self.actionExit = QtWidgets.QAction(self)
        self.actionExit.setObjectName("actionExit")
        self.menuArchivo.addAction(self.actionOpen)
        self.menuArchivo.addAction(self.actionSave)
        self.menuArchivo.addAction(self.actionDownload)
        self.menuArchivo.addAction(self.actionExport_PDF)
        self.menuArchivo.addAction(self.actionExit)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuAbout_HRV.menuAction())

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "HRV"))
        self.logo.setText(_translate("self", "<html><head/><body><p><img src=\":/logo/logo.svg\"/></p></body></html>"))
        self.fileNameLabel.setText(_translate("self", "File name:"))
        self.recordNameLabel.setText(_translate("self", "Record name:"))
        self.fsLabel.setText(_translate("self", "FS:"))
        self.lenghtSignalLabel.setText(_translate("self", "Lenght signal:"))
        self.fileNameText.setText(_translate("self", "fileNameText"))
        self.recordNameText.setText(_translate("self", "recordNameText"))
        self.fsText.setText(_translate("self", "fsText"))
        self.lenghtSignalText.setText(_translate("self", "lenghtSignalText"))
        self.completeBrief.setText(_translate("self", "Complete brief"))
        self.normalGraphic.setText(_translate("self", "Normal Graphic"))
        self.baseLineCorrection.setText(_translate("self", "Base Line Correction"))
        self.rDots.setText(_translate("self", "Picos R"))
        self.frequencyMetrics.setText(_translate("self", "Métricas de la Frecuencia"))
        self.pdfExport.setText(_translate("self", "Export PDF"))
        self.menuArchivo.setTitle(_translate("self", "File"))
        self.menuAbout_HRV.setTitle(_translate("self", "About HRV"))
        self.actionOpen.setText(_translate("self", "Open"))
        self.actionSave.setText(_translate("self", "Save"))
        self.actionDownload.setText(_translate("self", "Download"))
        self.actionExport_PDF.setText(_translate("self", "Export PDF"))
        self.actionExit.setText(_translate("self", "Exit"))
import resources_rc
